import java.util.Scanner;
import java.io.IOException;
import java.lang.InterruptedException;
import java.io.FileWriter;
import java.io.PrintWriter;

// ANSI escape codes for colors
public class EnhancedTypingTest {
    public static final String RESET = "\033[0m";  // Text Reset
    public static final String RED = "\033[0;31m";    // RED
    public static final String GREEN = "\033[0;32m";  // GREEN
    public static final String YELLOW = "\033[0;33m"; // YELLOW
    public static final String CYAN = "\033[0;36m";   // CYAN

    public static void accuracy(String sentence, String my_sentence) {
        double correctChars = 0;
        double totalChars = sentence.length();
        int minLength = Math.min(sentence.length(), my_sentence.length());

        for (int i = 0; i < minLength; i++) {
            if (sentence.charAt(i) == my_sentence.charAt(i)) {
                correctChars++;
            }
        }

        double accuracy = (correctChars / totalChars) * 100;
        System.out.printf(CYAN + "Your accuracy is %.2f%%\n" + RESET, accuracy);
    }

    public static void generateReport(String userName, String sentence, String my_sentence, double wpm, double seconds) {
        try (FileWriter fileWriter = new FileWriter(userName + "_typing_test_report.txt");
             PrintWriter printWriter = new PrintWriter(fileWriter)) {

            printWriter.println(GREEN + "========================================");
            printWriter.println("        Typing Test Report");
            printWriter.println("========================================" + RESET);
            printWriter.println(YELLOW + "Name: " + RESET + userName);
            printWriter.println(YELLOW + "Sentence: " + RESET + "\"" + sentence + "\"");
            printWriter.println(YELLOW + "Your Typing: " + RESET + "\"" + my_sentence + "\"");
            printWriter.printf(YELLOW + "Time Taken: %.2f seconds\n" + RESET, seconds);
            printWriter.printf(YELLOW + "Words Per Minute (WPM): %.2f\n" + RESET, wpm);

            if (sentence.equals(my_sentence)) {
                printWriter.println(GREEN + "Accuracy: 100%" + RESET);
            } else {
                double correctChars = 0;
                double totalChars = sentence.length();
                int minLength = Math.min(sentence.length(), my_sentence.length());

                for (int i = 0; i < minLength; i++) {
                    if (sentence.charAt(i) == my_sentence.charAt(i)) {
                        correctChars++;
                    }
                }

                double accuracy = (correctChars / totalChars) * 100;
                printWriter.printf(CYAN + "Accuracy: %.2f%%\n" + RESET, accuracy);
            }

            printWriter.println(GREEN + "\n========================================");
            printWriter.println("This report was generated by Siddhanth");
            printWriter.println("========================================" + RESET);

            System.out.println(GREEN + "Report generated successfully: " + userName + "_typing_test_report.txt" + RESET);
        } catch (IOException e) {
            System.out.println(RED + "Error generating report: " + e.getMessage() + RESET);
        }
    }

    public static void main(String[] args) {
        String sentence = "Hello, this is my channel";
        Scanner input = new Scanner(System.in);

        System.out.print(GREEN + "Please enter your name: " + RESET);
        String userName = input.nextLine();

        System.out.println(GREEN + "========================================");
        System.out.println("      Welcome to the Enhanced Typing Test!");
        System.out.println("========================================" + RESET);
        System.out.println(YELLOW + "Instructions:" + RESET);
        System.out.println("1. Type the following sentence exactly as it appears.");
        System.out.println("2. Your accuracy and words per minute (WPM) will be calculated.");
        System.out.println("3. Press Enter when you're done.\n");

        System.out.println(CYAN + "Sentence: \n\"" + sentence + "\"\n" + RESET);

        System.out.print(GREEN + "Press Enter when you are ready to start..." + RESET);
        input.nextLine();  // Wait for user to start

        long startTime = System.currentTimeMillis();
        System.out.print(YELLOW + "Start typing: " + RESET);
        String my_sentence = input.nextLine();
        long endTime = System.currentTimeMillis();

        long totalTime = endTime - startTime;
        double seconds = totalTime / 1000.0;
        double words = sentence.split(" ").length;
        double wpm = (words / seconds) * 60;

        System.out.printf(CYAN + "\nYour typing speed: %.2f WPM\n" + RESET, wpm);
        System.out.printf(CYAN + "You took %.2f seconds to complete.\n" + RESET, seconds);

        if (sentence.equals(my_sentence)) {
            System.out.println(GREEN + "Wow! Your accuracy is 100%!" + RESET);
        } else {
            accuracy(sentence, my_sentence);
        }

        input.close();

        // Call Python script to record typing speed and generate graph
        invokePythonScript("record_speed.py", userName, String.valueOf(wpm), String.valueOf(seconds));

        // Generate report
        generateReport(userName, sentence, my_sentence, wpm, seconds);

        // Ending note
        System.out.println(GREEN + "\n========================================");
        System.out.println("This program was developed by Siddhanth");
        System.out.println("========================================" + RESET);
    }

    public static void invokePythonScript(String scriptName, String userName, String... arguments) {
        try {
            ProcessBuilder pb = new ProcessBuilder("python", scriptName, userName, arguments[0], arguments[1]);
            Process p = pb.start();
            p.waitFor();
        } catch (IOException e) {
            System.out.println(RED + "Error executing Python script: " + e.getMessage() + RESET);
        } catch (InterruptedException e) {
            System.out.println(RED + "Python script execution was interrupted: " + e.getMessage() + RESET);
        }
    }
}
